name: Test Telegram Topics
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message to send'
        required: true
        type: string
        default: 'This is a test message'
      topic_id:
        description: 'Topic ID to send to (1, 2, 3, etc)'
        required: true
        type: string
        default: '1'

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug inputs
        run: |
          echo "Message: ${{ github.event.inputs.message }}"
          echo "Topic ID: ${{ github.event.inputs.topic_id }}"
          
      - name: Send message to specific topic
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          # Using args parameter for message_thread_id as it's not officially supported
          args: |
            -message.thread.id=${{ github.event.inputs.topic_id }}
          message: |
            📣 TEST MESSAGE TO TOPIC ${{ github.event.inputs.topic_id }}
            
            ${{ github.event.inputs.message }}
            
            If you see this message in the right topic, the topic ID is correct.
          format: markdown
          debug: true 