name: Test Topic Direct API
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message to send'
        required: true
        type: string
        default: 'This is a test message'
      topic_id:
        description: 'Topic ID to send to (1, 2, 3, etc)'
        required: true
        type: string
        default: '2'

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug inputs
        run: |
          echo "Message: ${{ github.event.inputs.message }}"
          echo "Topic ID: ${{ github.event.inputs.topic_id }}"
          
      - name: Send message to specific topic (Direct API)
        run: |
          MESSAGE="📣 TEST MESSAGE TO TOPIC ${{ github.event.inputs.topic_id }}

          ${{ github.event.inputs.message }}
          
          If you see this message in the right topic, the topic ID is correct."
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_TO }}" \
            -d "message_thread_id=${{ github.event.inputs.topic_id }}" \
            -d "text=$MESSAGE" \
            -d "parse_mode=Markdown" | jq 